#!/usr/bin/env python3
"""Generate shell/fish/completions/bigletters.fish from the real argument parser,
so the completions never drift from the program.   python3 tools/gen_fish_completions.py"""
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)

from bigletters import cli, fx, font  # noqa: E402

CHOICES = {name: " ".join(names) + " random" for name, names in fx.AXIS_NAMES.items()}
CHOICES["font"] = " ".join(font.FONT_NAMES) + " random"
CHOICES["theme"] = " ".join(fx.THEME_NAMES) + " random"


def quote(text):
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def generate():
    out = ["# bigletters-managed", "# generated by tools/gen_fish_completions.py - do not edit by hand",
           "complete -c bigletters -f"]
    for a in cli.build_parser()._actions:
        for opt in a.option_strings:
            if not opt.startswith("--") or opt == "--help":
                continue
            name = opt[2:]
            line = "complete -c bigletters -l %s" % name
            flag = a.nargs == 0                      # --clock, --bell ...: no value
            choices = CHOICES.get(name) or (" ".join(a.choices) if a.choices else None)
            if flag:
                pass
            elif choices:
                line += " -x -a %s" % quote(choices)
            elif name in ("file", "record"):
                line += " -r -F"
            elif a.nargs == "?":
                if name == "auto":
                    line += " -a %s" % quote("3 5 10")
            else:
                line += " -x"
            if a.help:
                desc = a.help.split("(")[0].split(":")[0].strip()
                line += " -d %s" % quote(desc)
            out.append(line)
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    path = os.path.join(ROOT, "shell", "fish", "completions", "bigletters.fish")
    with open(path, "w") as f:
        f.write(generate())
    print("wrote", path)
